//ajax
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

//auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CLEAN_LOGIN_ERROR = 'CLEAN_LOGIN_ERROR';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const UPGRADE_USER_TO_ADMIN_SUCCESS = 'UPGRADE_USER_TO_ADMIN_SUCCESS';
export const DOWNGRADE_ADMIN_TO_USER_SUCCESS = 'DOWNGRADE_ADMIN_TO_USER_SUCCESS';